all-headers: &all-headers
  - "*"

headers: &headers
  - Accept
  - Authorization

apply-headers: &apply-headers
  - Accept
  - Authorization
  - Referer
  - User-Agent

bat-qa:
  service: bat-cdn-qa
  headers: *all-headers
  domain:
    - qa.find-postgraduate-teacher-training.service.gov.uk
    - qa.register-trainee-teachers.education.gov.uk
    - qa.api.publish-teacher-training-courses.service.gov.uk
    - qa.publish-teacher-training-courses.service.gov.uk
    - audit.register-trainee-teachers.education.gov.uk
    - traineeteacherportal-dv.education.gov.uk
    - qa2.find-postgraduate-teacher-training.service.gov.uk
bat-staging:
  service: bat-cdn-staging
  headers: *all-headers
  domain:
    - staging.find-postgraduate-teacher-training.service.gov.uk
    - staging.api.publish-teacher-training-courses.service.gov.uk
    - staging.publish-teacher-training-courses.service.gov.uk
    - staging2.find-postgraduate-teacher-training.service.gov.uk
    - pen.find-postgraduate-teacher-training.service.gov.uk
    - pen.api.publish-teacher-training-courses.service.gov.uk
    - pen.publish-teacher-training-courses.service.gov.uk
    - staging.register-trainee-teachers.education.gov.uk
    - traineeteacherportal-pp.education.gov.uk

register-qa:
  service: register-cdn-qa
  headers: *all-headers
  domain:
    - qa.register-trainee-teachers.service.gov.uk

register-staging:
  service: register-cdn-staging
  headers: *all-headers
  domain:
    - staging.register-trainee-teachers.service.gov.uk

register-prod:
  service: register-cdn-prod
  headers: *all-headers
  domain:
    - www.register-trainee-teachers.service.gov.uk

se-staging:
  service: schoolexperience-cdn-test
  headers: *all-headers
  domain:
    - schoolexperience-staging.education.gov.uk

git-staging:
  service: get-into-teaching-cdn-test
  headers: *all-headers
  domain:
    - staging-adviser-getintoteaching.education.gov.uk
    - staging-getintoteaching.education.gov.uk
    - staging-schoolexperience.education.gov.uk
git-assets-staging:
  service: get-into-teaching-cdn-test-assets
  cookies: false
  domain:
    - assets-staging-getintoteaching.education.gov.uk
bat-prod:
  service: bat-cdn-prod
  headers: *all-headers
  domain:
    - www.find-postgraduate-teacher-training.service.gov.uk
    - www2.find-postgraduate-teacher-training.service.gov.uk
    - www.register-trainee-teachers.education.gov.uk
    - sandbox.find-postgraduate-teacher-training.service.gov.uk
    - sandbox2.find-postgraduate-teacher-training.service.gov.uk
    - sandbox.api.publish-teacher-training-courses.service.gov.uk
    - sandbox.publish-teacher-training-courses.service.gov.uk
    - www.publish-teacher-training-courses.service.gov.uk
    - api.publish-teacher-training-courses.service.gov.uk
    - traineeteacherportal.education.gov.uk
git-assets-production:
  service: get-into-teaching-cdn-prod-assets
  cookies: false
  domain:
    - app-assets-getintoteaching.education.gov.uk
se-prod:
  service: schoolexperience-cdn-prod2
  headers: *all-headers
  domain:
    - schoolexperience.education.gov.uk
git-prod:
  service: get-into-teaching-cdn-prod
  headers: *all-headers
  domain:
    - adviser-getintoteaching.education.gov.uk
    - beta-adviser-getintoteaching.education.gov.uk
    - getintoteaching.education.gov.uk
    - beta-getintoteaching.education.gov.uk
apply-qa:
  service: apply-cdn-qa
  headers: *apply-headers
  domain:
    - qa.apply-for-teacher-training.service.gov.uk
    - qa.apply-for-teacher-training.education.gov.uk
apply-staging:
  service: apply-cdn-staging
  headers: *apply-headers
  domain:
    - staging.apply-for-teacher-training.service.gov.uk
    - staging.apply-for-teacher-training.education.gov.uk
apply-prod:
  service: apply-cdn-prod
  headers: *apply-headers
  domain:
    - www.apply-for-teacher-training.service.gov.uk
    - www.apply-for-teacher-training.education.gov.uk
    - sandbox.apply-for-teacher-training.service.gov.uk
    - sandbox.apply-for-teacher-training.education.gov.uk
bat-assets-qa:
  service: bat-cdn-assets-qa
  cookies: false
  domain:
    - qa-assets.apply-for-teacher-training.service.gov.uk
    - qa-assets.find-postgraduate-teacher-training.service.gov.uk
bat-assets-staging:
  service: bat-cdn-assets-staging
  cookies: false
  domain:
    - staging-assets.apply-for-teacher-training.service.gov.uk
    - staging-assets.find-postgraduate-teacher-training.service.gov.uk
bat-assets-prod:
  service: bat-cdn-assets-prod
  cookies: false
  domain:
    - assets.apply-for-teacher-training.service.gov.uk
    - sandbox-assets.apply-for-teacher-training.service.gov.uk
    - assets.find-postgraduate-teacher-training.service.gov.uk
    - sandbox-assets.find-postgraduate-teacher-training.service.gov.uk
tra-production:
  service: teacher-qualifications-api-cdn-production
  headers: *all-headers
  domain:
    - teacher-qualifications-api.education.gov.uk
tra-preprod:
  service: teacher-qualifications-api-cdn-preprod
  headers: *all-headers
  domain:
    - preprod-teacher-qualifications-api.education.gov.uk
tra-test:
  service: teacher-qualifications-api-cdn-test
  headers: *all-headers
  domain:
    - test-teacher-qualifications-api.education.gov.uk
tra-falt-production:
  service: find-a-lost-trn-cdn-production
  headers: *all-headers
  domain:
    - find-a-lost-trn.education.gov.uk
tra-falt-preprod:
  service: find-a-lost-trn-cdn-preprod
  headers: *all-headers
  domain:
    - preprod-find-a-lost-trn.education.gov.uk
tra-falt-test:
  service: find-a-lost-trn-cdn-test
  headers: *all-headers
  domain:
    - test-find-a-lost-trn.education.gov.uk
tra-falt-dev:
  service: find-a-lost-trn-cdn-dev
  headers: *all-headers
  domain:
    - dev-find-a-lost-trn.education.gov.uk
