headers: &headers
  - Accept
  - Authorization

apply-headers: &apply-headers
  - Accept
  - Authorization
  - Referer
  - User-Agent

bat-qa:
  service: bat-cdn-qa
  headers: *headers
  domain:
    - qa.find-postgraduate-teacher-training.service.gov.uk
    - qa.register-trainee-teachers.education.gov.uk
    - qa.api.publish-teacher-training-courses.service.gov.uk
    - qa.publish-teacher-training-courses.service.gov.uk
    - audit.register-trainee-teachers.education.gov.uk
bat-staging:
  service: bat-cdn-staging
  headers: *headers
  domain:
    - staging.find-postgraduate-teacher-training.service.gov.uk
    - staging.register-trainee-teachers.education.gov.uk
    - pen.register-trainee-teachers.education.gov.uk
    - staging.api.publish-teacher-training-courses.service.gov.uk
    - staging.publish-teacher-training-courses.service.gov.uk
git-staging:
  service: get-into-teaching-cdn-test
  headers: *headers
  domain:
    - staging-adviser-getintoteaching.education.gov.uk
    - staging-getintoteaching.education.gov.uk
    - staging-schoolexperience.education.gov.uk
bat-prod:
  service: bat-cdn-prod
  headers: *headers
  domain:
    - www2.find-postgraduate-teacher-training.service.gov.uk
    - www.find-postgraduate-teacher-training.service.gov.uk
    - www.register-trainee-teachers.education.gov.uk
    - sandbox.find-postgraduate-teacher-training.service.gov.uk
    - sandbox.api.publish-teacher-training-courses.service.gov.uk
    - sandbox.publish-teacher-training-courses.service.gov.uk
    - sandbox.register-trainee-teachers.education.gov.uk
    - www.publish-teacher-training-courses.service.gov.uk
    - api.publish-teacher-training-courses.service.gov.uk
git-prod:
  service: get-into-teaching-cdn-prod
  headers: *headers
  domain:
    - adviser-getintoteaching.education.gov.uk
    - beta-adviser-getintoteaching.education.gov.uk
    - getintoteaching.education.gov.uk
    - beta-getintoteaching.education.gov.uk
apply-qa:
  service: apply-cdn-qa
  headers: *apply-headers
  domain:
    - qa.apply-for-teacher-training.service.gov.uk
    - qa.apply-for-teacher-training.education.gov.uk
apply-staging:
  service: apply-cdn-staging
  headers: *apply-headers
  domain:
    - staging.apply-for-teacher-training.service.gov.uk
    - staging.apply-for-teacher-training.education.gov.uk
apply-prod:
  service: apply-cdn-prod
  headers: *apply-headers
  domain:
    - www.apply-for-teacher-training.service.gov.uk
    - www.apply-for-teacher-training.education.gov.uk
    - sandbox.apply-for-teacher-training.service.gov.uk
    - sandbox.apply-for-teacher-training.education.gov.uk
bat-assets-qa:
  service: bat-cdn-assets-qa
  cookies: false
  domain:
    - qa-assets.apply-for-teacher-training.service.gov.uk
bat-assets-staging:
  service: bat-cdn-assets-staging
  cookies: false
  domain:
    - staging-assets.apply-for-teacher-training.service.gov.uk
bat-assets-prod:
  service: bat-cdn-assets-prod
  cookies: false
  domain:
    - assets.apply-for-teacher-training.service.gov.uk
    - sandbox-assets.apply-for-teacher-training.service.gov.uk
