all-headers: &all-headers
  - "*"

headers: &headers
  - Accept
  - Authorization

se-staging:
  service: schoolexperience-cdn-test
  headers: *all-headers
  domain:
    - schoolexperience-staging.education.gov.uk

git-staging:
  service: get-into-teaching-cdn-test
  headers: *all-headers
  domain:
    - staging-adviser-getintoteaching.education.gov.uk
    - staging-getintoteaching.education.gov.uk
    - staging-schoolexperience.education.gov.uk
git-assets-staging:
  service: get-into-teaching-cdn-test-assets
  cookies: false
  domain:
    - assets-staging-getintoteaching.education.gov.uk
git-assets-production:
  service: get-into-teaching-cdn-prod-assets
  cookies: false
  domain:
    - app-assets-getintoteaching.education.gov.uk
se-prod:
  service: schoolexperience-cdn-prod2
  headers: *all-headers
  domain:
    - schoolexperience.education.gov.uk
git-prod:
  service: get-into-teaching-cdn-prod
  headers: *all-headers
  domain:
    - adviser-getintoteaching.education.gov.uk
    - beta-adviser-getintoteaching.education.gov.uk
    - getintoteaching.education.gov.uk
    - beta-getintoteaching.education.gov.uk
tra-production:
  service: teacher-qualifications-api-cdn-production
  headers: *all-headers
  domain:
    - teacher-qualifications-api.education.gov.uk
tra-preprod:
  service: teacher-qualifications-api-cdn-preprod
  headers: *all-headers
  domain:
    - preprod-teacher-qualifications-api.education.gov.uk
tra-test:
  service: teacher-qualifications-api-cdn-test
  headers: *all-headers
  domain:
    - test-teacher-qualifications-api.education.gov.uk
tra-falt-production:
  service: find-a-lost-trn-cdn-production
  headers: *all-headers
  domain:
    - find-a-lost-trn.education.gov.uk
tra-falt-preprod:
  service: find-a-lost-trn-cdn-preprod
  headers: *all-headers
  domain:
    - preprod-find-a-lost-trn.education.gov.uk
tra-falt-test:
  service: find-a-lost-trn-cdn-test
  headers: *all-headers
  domain:
    - test-find-a-lost-trn.education.gov.uk
tra-falt-dev:
  service: find-a-lost-trn-cdn-dev
  headers: *all-headers
  domain:
    - dev-find-a-lost-trn.education.gov.uk
