all-headers: &all-headers
  - "*"

headers: &headers
  - Accept
  - Authorization

git-staging:
  service: get-into-teaching-cdn-test
  headers: *all-headers
  domain:
    - staging-adviser-getintoteaching.education.gov.uk
    - staging-getintoteaching.education.gov.uk

git-assets-staging:
  service: get-into-teaching-cdn-test-assets
  cookies: false
  domain:
    - assets-staging-getintoteaching.education.gov.uk
git-assets-production:
  service: get-into-teaching-cdn-prod-assets
  cookies: false
  domain:
    - app-assets-getintoteaching.education.gov.uk

git-prod:
  service: get-into-teaching-cdn-prod
  headers: *all-headers
  domain:
    - adviser-getintoteaching.education.gov.uk
    - beta-adviser-getintoteaching.education.gov.uk
    - getintoteaching.education.gov.uk
    - beta-getintoteaching.education.gov.uk
