name: Prepare Environment Matrix
description: Step to prepare the environment matrix to be used for deployment.
inputs:
  available-environments:
    description: 'Comma separated list of available environments, eg: qa, staging, production'
    required: false
    default: qa, staging, production, sandbox, rollover
outputs:
  environments: 
    description: The environment matrix
    value: ${{ steps.select-environments.outputs.environments }}
runs:
  using: composite
  steps: 
    - name:  Prepare Environment Matrix
      shell: pwsh
      id:    select-environments
      run: |
        $inputs = '${{ toJson(github.event.inputs) }}' | ConvertFrom-Json -AsHashtable
        $environments = '${{ inputs.available-environments }}'.Split(',').Trim().Where{ $inputs[$_] -eq 'true' }
        echo "Selected Environments => [$($environments)]"
        echo "::set-output name=environments::$(@{ environment = $environments } | ConvertTo-Json -Compress)"
