name: Check users with space developer role

on:
  schedule: # Midnight every day
    - cron: '0 0 * * *'

jobs:
  CHECK-SPACE-USER:
    runs-on: ubuntu-latest
    steps:
      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USER_PROD }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD_PROD }}
          CF_SPACE_NAME: bat-prod
          CF_ORG_NAME: dfe
          CF_API_URL:  https://api.london.cloud.service.gov.uk
          INSTALL_CONDUIT: false


      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run powershell script
        shell: pwsh
        run: |
          ./scripts/check-users-in-space-developer-role.ps1 `
            -Space "${{ env.CF_SPACE_NAME }}" `
            -SlackWebhook "${{secrets.SLACK_WEBHOOK}}" `
            -Unset `
            -Whitelist "${{secrets.PAAS_USER_WHITELIST}}"
        env:
          CF_SPACE_NAME: bat-prod
