name: Deploy Prometheus & Grafana

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy, qa or prod
        required: true
        type: choice
        options:
          - qa
          - prod
        default: qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set environment variables
        run: |
          echo "MONITORING_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: azure/login@v1
        with:
          creds: ${{ secrets[format('AZURE_CREDENTIALS_{0}', env.MONITORING_ENV)] }}

      - name: Validate secrets
        run: make $MONITORING_ENV validate-infra-secrets
        env:
          CONFIRM_PRODUCTION: yes

      - name: Setup Terraform v0.15.5
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Terraform init, plan & apply
        run: make $MONITORING_ENV ci monitoring-apply
        env:
          ARM_ACCESS_KEY: ${{ secrets[format('TERRAFORM_STATE_ACCESS_KEY_{0}', env.MONITORING_ENV)] }}
          TF_VAR_azure_credentials: ${{ secrets[format('AZURE_CREDENTIALS_{0}', env.MONITORING_ENV)] }}
          CONFIRM_PRODUCTION: yes
